// ═══════════════════════════════════════════════════════════════
//  WebQuote — odvetvové dáta
//  Adaptívne výbery podľa odvetvia + odporúčané štruktúry sekcií
// ═══════════════════════════════════════════════════════════════

// ── PRÁVNE OBLASTI (zdroj: lexante.sk → Služby) ──────────────
export const LEGAL_AREAS = [
  { id:"corporate",   label:"Obchodné právo a právo obchodných spoločností", en:"Commercial & corporate law" },
  { id:"disputes",    label:"Riešenie sporov",                               en:"Dispute resolution" },
  { id:"ip",          label:"Právo duševného vlastníctva",                   en:"Intellectual property law" },
  { id:"realestate",  label:"Nehnuteľnosti a development",                   en:"Real estate & development" },
  { id:"banking",     label:"Bankové a finančné právo",                      en:"Banking & finance law" },
  { id:"it",          label:"Právo informačných technológií",                en:"IT & technology law" },
  { id:"media",       label:"Mediálne právo, ochrana osobnosti a dobrej povesti", en:"Media law & personality rights" },
  { id:"privacy",     label:"Ochrana súkromia a osobných údajov (GDPR)",     en:"Privacy & data protection (GDPR)" },
  { id:"civil",       label:"Občianske právo",                               en:"Civil law" },
  { id:"labor",       label:"Pracovné právo",                                en:"Labour law" },
  { id:"admin",       label:"Správne právo",                                 en:"Administrative law" },
  { id:"criminal",    label:"Trestné právo",                                 en:"Criminal law" },
];

// ── ADAPTÍVNE VÝBERY PODĽA ODVETVIA ──────────────────────────
// Po zvolení odvetvia sa zobrazí ďalší multi-výber, ktorý spresní
// brief aj generovaný prompt. Kľúč = industry id, voliteľne subcat.
const EXTRAS = {
  automotive: { title:"Ponúkané služby", en:"Services offered", options:[
    { id:"sale",       label:"Predaj vozidiel",          en:"Vehicle sales" },
    { id:"service",    label:"Servis a opravy",          en:"Service & repairs" },
    { id:"tires",      label:"Pneuservis",               en:"Tire service" },
    { id:"aircon",     label:"Klimatizácie",             en:"A/C service" },
    { id:"geometry",   label:"Geometria náprav",         en:"Wheel alignment" },
    { id:"stk",        label:"STK / EK zabezpečenie",    en:"Vehicle inspection arrangement" },
    { id:"towing",     label:"Odťahová služba",          en:"Towing service" },
    { id:"financing",  label:"Financovanie / leasing",   en:"Financing / leasing" },
    { id:"buyout",     label:"Výkup vozidiel",           en:"Vehicle buyout" },
    { id:"rental",     label:"Požičovňa vozidiel",       en:"Car rental" },
  ]},
  creative: { title:"Zameranie tvorby", en:"Creative focus", options:[
    { id:"weddings",   label:"Svadby",                   en:"Weddings" },
    { id:"portraits",  label:"Portréty",                 en:"Portraits" },
    { id:"product",    label:"Produktová tvorba",        en:"Product work" },
    { id:"events",     label:"Eventy / reportáže",       en:"Events / coverage" },
    { id:"commercial", label:"Komerčná tvorba pre firmy",en:"Commercial work" },
    { id:"video",      label:"Video produkcia",          en:"Video production" },
    { id:"drone",      label:"Drone zábery",             en:"Drone footage" },
    { id:"studio",     label:"Vlastné štúdio",           en:"Own studio" },
    { id:"workshops",  label:"Workshopy / kurzy",        en:"Workshops / courses" },
    { id:"prints",     label:"Predaj printov / diel",    en:"Prints / art sales" },
  ]},
  ecommerce: { title:"Model predaja", en:"Sales model", options:[
    { id:"physical",   label:"Fyzické produkty",         en:"Physical products" },
    { id:"digital",    label:"Digitálne produkty",       en:"Digital products" },
    { id:"subscription",label:"Predplatné",              en:"Subscriptions" },
    { id:"custom",     label:"Personalizácia produktov", en:"Product personalisation" },
    { id:"b2b",        label:"B2B veľkoobchod",          en:"B2B wholesale" },
    { id:"clickcollect",label:"Osobný odber (click & collect)", en:"Click & collect" },
    { id:"intl",       label:"Medzinárodná doprava",     en:"International shipping" },
    { id:"loyalty",    label:"Vernostný program",        en:"Loyalty programme" },
    { id:"vouchers",   label:"Darčekové poukazy",        en:"Gift vouchers" },
  ]},
  education: { title:"Formát vzdelávania", en:"Education format", options:[
    { id:"group",      label:"Skupinové kurzy",          en:"Group courses" },
    { id:"individual", label:"Individuálne hodiny",      en:"1-on-1 lessons" },
    { id:"online",     label:"Online kurzy",             en:"Online courses" },
    { id:"corporate",  label:"Firemné školenia",         en:"Corporate training" },
    { id:"certs",      label:"Certifikácie",             en:"Certifications" },
    { id:"kids",       label:"Kurzy pre deti",           en:"Kids' courses" },
    { id:"camps",      label:"Tábory / sústredenia",     en:"Camps" },
    { id:"tutoring",   label:"Doučovanie",               en:"Tutoring" },
    { id:"elearning",  label:"E-learning platforma",     en:"E-learning platform" },
  ]},
  finance: { title:"Finančné služby", en:"Financial services", options:[
    { id:"loans",      label:"Úvery a hypotéky",         en:"Loans & mortgages" },
    { id:"investments",label:"Investície",               en:"Investments" },
    { id:"insurance",  label:"Poistenie",                en:"Insurance" },
    { id:"pension",    label:"Dôchodkové sporenie",      en:"Pension savings" },
    { id:"accounting", label:"Účtovníctvo",              en:"Accounting" },
    { id:"tax",        label:"Daňové poradenstvo",       en:"Tax advisory" },
    { id:"crypto",     label:"Krypto / digitálne aktíva",en:"Crypto / digital assets" },
    { id:"corporate",  label:"Firemné financie",         en:"Corporate finance" },
    { id:"planning",   label:"Osobný finančný plán",     en:"Personal financial planning" },
  ]},
  gastro: { title:"Ponuka a služby", en:"Offering & services", options:[
    { id:"dailymenu",  label:"Denné menu",               en:"Daily menu" },
    { id:"alacarte",   label:"À la carte",               en:"À la carte" },
    { id:"brunch",     label:"Raňajky / brunch",         en:"Breakfast / brunch" },
    { id:"delivery",   label:"Rozvoz",                   en:"Delivery" },
    { id:"takeaway",   label:"Take-away",                en:"Take-away" },
    { id:"catering",   label:"Catering",                 en:"Catering" },
    { id:"privateevents",label:"Súkromné akcie",         en:"Private events" },
    { id:"tastings",   label:"Degustácie",               en:"Tastings" },
    { id:"vegan",      label:"Vegetariánske / vegánske", en:"Vegetarian / vegan" },
    { id:"glutenfree", label:"Bezlepkové možnosti",      en:"Gluten-free options" },
    { id:"terrace",    label:"Terasa",                   en:"Terrace" },
    { id:"kids",       label:"Detský kútik",             en:"Kids' corner" },
  ]},
  health: { title:"Poskytovaná starostlivosť", en:"Care provided", options:[
    { id:"prevention", label:"Preventívne prehliadky",   en:"Preventive check-ups" },
    { id:"specialist", label:"Špecializované vyšetrenia",en:"Specialist examinations" },
    { id:"diagnostics",label:"Diagnostika / ultrazvuk",  en:"Diagnostics / ultrasound" },
    { id:"vaccination",label:"Očkovanie",                en:"Vaccination" },
    { id:"telemedicine",label:"Telemedicína / online konzultácie", en:"Telemedicine" },
    { id:"homecare",   label:"Domáca starostlivosť",     en:"Home care" },
    { id:"lab",        label:"Laboratórne testy",        en:"Laboratory tests" },
    { id:"aesthetics", label:"Estetická medicína",       en:"Aesthetic medicine" },
    { id:"rehab",      label:"Rehabilitácia",            en:"Rehabilitation" },
    { id:"insurances", label:"Zazmluvnené poisťovne",    en:"Contracted insurers" },
  ]},
  manufacturing: { title:"Výrobné kapacity a služby", en:"Production capabilities", options:[
    { id:"custom",     label:"Zákazková výroba",         en:"Custom manufacturing" },
    { id:"serial",     label:"Sériová výroba",           en:"Serial production" },
    { id:"prototyping",label:"Prototypovanie",           en:"Prototyping" },
    { id:"cnc",        label:"CNC obrábanie",            en:"CNC machining" },
    { id:"welding",    label:"Zváranie",                 en:"Welding" },
    { id:"finishing",  label:"Povrchové úpravy",         en:"Surface finishing" },
    { id:"assembly",   label:"Montáž",                   en:"Assembly" },
    { id:"logistics",  label:"Logistika / doprava",      en:"Logistics" },
    { id:"iso",        label:"Certifikácie (ISO...)",    en:"Certifications (ISO...)" },
    { id:"rnd",        label:"Vývoj a konštrukcia",      en:"R&D / engineering" },
  ]},
  nonprofit: { title:"Aktivity organizácie", en:"Organisation activities", options:[
    { id:"volunteering",label:"Dobrovoľníctvo",          en:"Volunteering" },
    { id:"donations",  label:"Darcovstvo / fundraising", en:"Donations / fundraising" },
    { id:"membership", label:"Členstvo",                 en:"Membership" },
    { id:"collections",label:"Verejné zbierky",          en:"Public collections" },
    { id:"grants",     label:"Granty a projekty",        en:"Grants & projects" },
    { id:"community",  label:"Komunitné akcie",          en:"Community events" },
    { id:"education",  label:"Vzdelávacie programy",     en:"Educational programmes" },
    { id:"advocacy",   label:"Advokácia / osveta",       en:"Advocacy / awareness" },
    { id:"transparency",label:"Transparentné financovanie", en:"Financial transparency" },
  ]},
  pets: { title:"Služby pre zvieratá", en:"Pet services", options:[
    { id:"vetcare",    label:"Veterinárna starostlivosť",en:"Veterinary care" },
    { id:"vaccination",label:"Očkovanie a čipovanie",    en:"Vaccination & microchipping" },
    { id:"surgery",    label:"Chirurgia",                en:"Surgery" },
    { id:"grooming",   label:"Grooming / úprava srsti",  en:"Grooming" },
    { id:"boarding",   label:"Hotel / penzión",          en:"Boarding" },
    { id:"training",   label:"Výcvik",                   en:"Training" },
    { id:"food",       label:"Predaj krmív a potrieb",   en:"Food & supplies" },
    { id:"breeding",   label:"Chov",                     en:"Breeding" },
    { id:"emergency",  label:"Pohotovosť",               en:"Emergency service" },
  ]},
  public: { title:"Funkcie pre občanov", en:"Citizen services", options:[
    { id:"board",      label:"Úradná tabuľa",            en:"Official notice board" },
    { id:"eforms",     label:"Elektronické formuláre",   en:"Electronic forms" },
    { id:"minutes",    label:"Zápisnice a uznesenia",    en:"Minutes & resolutions" },
    { id:"procurement",label:"Verejné obstarávanie",     en:"Public procurement" },
    { id:"culture",    label:"Kultúrne podujatia",       en:"Cultural events" },
    { id:"reporting",  label:"Hlásenie porúch / podnetov", en:"Issue reporting" },
    { id:"waste",      label:"Odpadový kalendár",        en:"Waste calendar" },
    { id:"budget",     label:"Participatívny rozpočet",  en:"Participatory budget" },
  ]},
  realty: { title:"Rozsah služieb", en:"Scope of services", options:[
    { id:"sale",       label:"Predaj nehnuteľností",     en:"Property sales" },
    { id:"rental",     label:"Prenájom",                 en:"Rentals" },
    { id:"management", label:"Správa nehnuteľností",     en:"Property management" },
    { id:"construction",label:"Výstavba na kľúč",        en:"Turnkey construction" },
    { id:"renovation", label:"Rekonštrukcie",            en:"Renovations" },
    { id:"interior",   label:"Interiérový dizajn",       en:"Interior design" },
    { id:"appraisal",  label:"Znalecké posudky",         en:"Appraisals" },
    { id:"mortgage",   label:"Hypotekárne poradenstvo",  en:"Mortgage advisory" },
    { id:"tours3d",    label:"3D obhliadky",             en:"3D tours" },
    { id:"staging",    label:"Home staging",             en:"Home staging" },
  ]},
  services: { title:"Rozsah služieb", en:"Scope of services", options:[
    { id:"consulting", label:"Konzultácie",              en:"Consulting" },
    { id:"audit",      label:"Audit / analýza",          en:"Audit / analysis" },
    { id:"implementation",label:"Implementácia riešení", en:"Implementation" },
    { id:"outsourcing",label:"Outsourcing",              en:"Outsourcing" },
    { id:"training",   label:"Školenia",                 en:"Training" },
    { id:"support",    label:"Podpora / servis",         en:"Support / maintenance" },
    { id:"contracts",  label:"Zmluvná spolupráca",       en:"Contract-based cooperation" },
  ]},
  sportoutdoor: { title:"Ponuka klubu / centra", en:"Club / centre offering", options:[
    { id:"membership", label:"Členstvá",                 en:"Memberships" },
    { id:"training",   label:"Tréningy",                 en:"Training sessions" },
    { id:"kids",       label:"Kurzy pre deti",           en:"Kids' courses" },
    { id:"rental",     label:"Prenájom výstroja",        en:"Equipment rental" },
    { id:"trips",      label:"Organizované výlety",      en:"Guided trips" },
    { id:"races",      label:"Závody / turnaje",         en:"Races / tournaments" },
    { id:"camps",      label:"Sústredenia",              en:"Training camps" },
    { id:"schedule",   label:"Online rozvrh",            en:"Online schedule" },
  ]},
  tech: { title:"Vlastnosti produktu / služby", en:"Product / service traits", options:[
    { id:"trial",      label:"Free trial",               en:"Free trial" },
    { id:"demo",       label:"Demo na vyžiadanie",       en:"Bookable demo" },
    { id:"api",        label:"API / integrácie",         en:"API / integrations" },
    { id:"onprem",     label:"On-premise nasadenie",     en:"On-premise deployment" },
    { id:"whitelabel", label:"White-label",              en:"White-label" },
    { id:"sla",        label:"Podpora so SLA",           en:"SLA-backed support" },
    { id:"migration",  label:"Migrácia dát",             en:"Data migration" },
    { id:"security",   label:"Security / compliance",    en:"Security / compliance" },
    { id:"docs",       label:"Dokumentácia / dev portál",en:"Docs / dev portal" },
  ]},
  travel: { title:"Ponuka služieb", en:"Services offered", options:[
    { id:"accommodation",label:"Ubytovanie",             en:"Accommodation" },
    { id:"custom",     label:"Zájazdy na mieru",         en:"Tailor-made trips" },
    { id:"group",      label:"Skupinové zájazdy",        en:"Group tours" },
    { id:"flights",    label:"Letenky",                  en:"Flights" },
    { id:"insurance",  label:"Cestovné poistenie",       en:"Travel insurance" },
    { id:"transfers",  label:"Transfery",                en:"Transfers" },
    { id:"guides",     label:"Sprievodcovské služby",    en:"Guided tours" },
    { id:"corporate",  label:"Firemné akcie / teambuilding", en:"Corporate events" },
    { id:"lastminute", label:"Last minute ponuky",       en:"Last minute deals" },
  ]},
  wellness: { title:"Procedúry a služby", en:"Treatments & services", options:[
    { id:"massage",    label:"Masáže",                   en:"Massages" },
    { id:"spa",        label:"Sauna / spa rituály",      en:"Sauna / spa rituals" },
    { id:"cosmetics",  label:"Kozmetika",                en:"Cosmetics" },
    { id:"hair",       label:"Kaderníctvo",              en:"Hairdressing" },
    { id:"passes",     label:"Permanentky",              en:"Passes" },
    { id:"vouchers",   label:"Darčekové poukazy",        en:"Gift vouchers" },
    { id:"couples",    label:"Párové procedúry",         en:"Couple treatments" },
    { id:"booking",    label:"Online rezervácie",        en:"Online booking" },
    { id:"products",   label:"Produkty na predaj",       en:"Retail products" },
  ]},
};

// Špecifické výbery pre podkategórie (prepíšu default odvetvia)
const EXTRAS_BY_SUBCAT = {
  law: { title:"Oblasti práva", en:"Practice areas", options: LEGAL_AREAS },
  accounting: { title:"Účtovné a daňové služby", en:"Accounting & tax services", options:[
    { id:"single",     label:"Jednoduché účtovníctvo",   en:"Single-entry bookkeeping" },
    { id:"double",     label:"Podvojné účtovníctvo",     en:"Double-entry bookkeeping" },
    { id:"payroll",    label:"Mzdy a personalistika",    en:"Payroll & HR" },
    { id:"taxreturns", label:"Daňové priznania",         en:"Tax returns" },
    { id:"vat",        label:"DPH agenda",               en:"VAT agenda" },
    { id:"reporting",  label:"Reporting / výkazy",       en:"Reporting" },
    { id:"audit",      label:"Audit",                    en:"Audit" },
    { id:"incorporation",label:"Zakladanie firiem",      en:"Company incorporation" },
  ]},
};

// Vráti adaptívny výber pre kombináciu odvetvie + podkategória.
export function getIndustryExtras(industry, subcat) {
  if (subcat && EXTRAS_BY_SUBCAT[subcat]) return EXTRAS_BY_SUBCAT[subcat];
  return EXTRAS[industry] || null;
}

// ── ODPORÚČANÁ ŠTRUKTÚRA SEKCIÍ PODĽA ODVETVIA ───────────────
export const INDUSTRY_SECTION_PRESETS = {
  automotive:    ["nav","hero","services","features","gallery","testimonials","faq","contact","map","openinghours","cta","footer","cookies","scrolltop"],
  creative:      ["nav","hero","work","gallery","about","process","testimonials","pricing","contact","footer","scrolltop"],
  ecommerce:     ["nav","hero","products","features","testimonials","faq","newsletter","cta","footer","cookies","scrolltop","search"],
  education:     ["nav","hero","services","process","team","pricing","testimonials","faq","leadform","contact","footer","cookies","scrolltop"],
  finance:       ["nav","hero","services","stats","process","team","testimonials","faq","calculator","leadform","contact","footer","cookies","scrolltop"],
  gastro:        ["nav","hero","menu","about","gallery","reviews","map","openinghours","booking","contact","footer","cookies","scrolltop"],
  health:        ["nav","hero","services","team","pricing","faq","booking","contact","map","openinghours","footer","cookies","scrolltop"],
  manufacturing: ["nav","hero","about","services","products","stats","partners","awards","leadform","contact","map","footer","cookies","scrolltop"],
  nonprofit:     ["nav","hero","about","events","stats","team","partners","cta","newsletter","contact","footer","cookies","scrolltop"],
  pets:          ["nav","hero","services","team","pricing","gallery","reviews","booking","contact","map","openinghours","footer","cookies","scrolltop"],
  public:        ["nav","hero","about","events","blog","faq","map","openinghours","contact","footer","cookies","scrolltop","search"],
  realty:        ["nav","hero","products","about","team","stats","testimonials","process","leadform","contact","map","footer","cookies","scrolltop"],
  services:      ["nav","hero","services","about","team","stats","testimonials","faq","leadform","contact","map","footer","cookies","scrolltop"],
  sportoutdoor:  ["nav","hero","about","services","events","gallery","pricing","team","faq","contact","map","footer","cookies","scrolltop"],
  tech:          ["nav","hero","features","process","pricing","testimonials","logos","faq","cta","newsletter","footer","cookies","scrolltop","darkmode"],
  travel:        ["nav","hero","services","gallery","testimonials","faq","booking","map","newsletter","contact","footer","cookies","scrolltop"],
  wellness:      ["nav","hero","services","pricing","gallery","team","testimonials","booking","contact","openinghours","footer","cookies","scrolltop"],
};
